Loja.Mvc/Areas/Vendas/Controllers/LeiloesController.cs
using Loja.Dominio;
using Loja.Mvc.Helpers;
using Loja.Repositorios.SqlServer.EF;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Security.Claims;
using System.Web;
using System.Web.Mvc;

namespace Loja.Mvc.Areas.Vendas.Controllers
{
    [Authorize]
    public class LeiloesController : Controller
    {
        private LojaDbContext _db = new LojaDbContext();

        // GET: Vendas/Leiloes
        [AllowAnonymous]
        public ActionResult Index()
        {
            return View(Mapeamento.Mapear(_db.Produtos.Where(i => i.EmLeilao).ToList()));
        }

        // GET: Produtos/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var usuario = (ClaimsIdentity) User.Identity;

            if (!usuario.HasClaim(Modulo.Leilao.ToString(), Acao.Detalhar.ToString()))
            {
                return RedirectToAction("Login", "Account", new { Area = "" });
            }

            Produto produto = _db.Produtos.Find(id);
            if (produto == null)
            {
                return HttpNotFound();
            }
            return View(Mapeamento.Mapear(produto));
        }

        public ActionResult Create()
        {
            return View();
        }
    }
}

Loja.Mvc/Views/Shared/_CulturaParcial.cshtml
@using Loja.Mvc.Helpers
@{ var cultura = new CulturaHelper(); }

<ul class="nav navbar-nav navbar-right">
    <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <img src="~/Content/blank.gif" alt="@cultura.NomeNativo" title="@cultura.NomeNativo" class="flag flag-@cultura.Abreviacao" />
            <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
            <li>
                <a href="@Url.Action("DefinirLinguagem", "Home", new { Area = "", linguagem = "pt-BR" })">
                    <img src="~/Content/blank.gif" alt="Brasil" title="Brasil" class="flag flag-br" />
                    Brasil
                </a>
            </li>
            <li>
                <a href="@Url.Action("DefinirLinguagem", "Home", new { Area = "", linguagem = "es" })">
                    <img src="~/Content/blank.gif" alt="España" title="España" class="flag flag-es" />
                    España
                </a>
            </li>
            <li>
                <a href="@Url.Action("DefinirLinguagem", "Home", new { Area = "", linguagem = "en-US" })">
                    <img src="~/Content/blank.gif" alt="USA" title="USA" class="flag flag-us" />
                    USA
                </a>
            </li>
        </ul>
    </li>
</ul>

Loja.Mvc/Views/Shared/_Layout.cshtml
@using Loja.Dominio
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>@ViewBag.Title - My ASP.NET Application</title>
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
    </head>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Home", "Index", "Home", new { Area = "" }, null)</li>
                        <li>@Html.ActionLink("About", "About", "Home", new { Area = "" }, null)</li>
                        <li>@Html.ActionLink("Contact", "Contact", "Home", new { Area = "" }, null)</li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Vendas <b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("Produtos", "Index", "Produtos", new { Area = "Vendas" }, null)</li>
                                <li class="divider" />

@*                                @if (User.IsInRole(Perfil.Master.ToString())) {*@
                                <li>@Html.ActionLink("Leilões", "Index", "Leiloes", new { Area = "Vendas" }, null)</li>
  @*                              }*@
                            </ul>
                        </li>
                    </ul>
                    @Html.Partial("_CulturaParcial")
                    @Html.Partial("_LoginPartial")
                </div>
            </div>
        </div>
        <div class="container body-content">
            @RenderBody()
            <hr />
            <footer>
                <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
            </footer>
        </div>

        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)
    </body>
</html>